name: budget_app_starting
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  cloud_firestore:
  firebase_auth:
  firebase_core: ^2.23.0
  flutter_hooks:
  hooks_riverpod:
  google_fonts:
  google_sign_in:
  sign_button: ^2.0.2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.14
  flutter_svg: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "Budget App"


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
