// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-qis5jQwcF5lIyy5INxbT09c1dEiM1U',
    appId: '1:650570498112:web:bc2b6abf7bd3d6df6f1fa5',
    messagingSenderId: '650570498112',
    projectId: 'budget-app-b8d08',
    authDomain: 'budget-app-b8d08.firebaseapp.com',
    storageBucket: 'budget-app-b8d08.appspot.com',
    measurementId: 'G-69QH18C2YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDameHutgtUgE7PgUaQ_Tqr_VmVbk9jNc',
    appId: '1:650570498112:android:a5c1bfbbd0d710146f1fa5',
    messagingSenderId: '650570498112',
    projectId: 'budget-app-b8d08',
    storageBucket: 'budget-app-b8d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SuX1FeqpE20bqfnH0FDAse-t0tOnBHo',
    appId: '1:650570498112:ios:1fb8919f87297ad46f1fa5',
    messagingSenderId: '650570498112',
    projectId: 'budget-app-b8d08',
    storageBucket: 'budget-app-b8d08.appspot.com',
    iosBundleId: 'com.codingliquids.budgetAppStarting',
  );
}
